version: "3.8"

services:
  geoapp:
    image: ebe/geo:latest
    depends_on:
      - mariadb
    build: .
    container_name: geomex
    volumes:
      - ./src:/app/src:rw
    env_file:
      - ./.env.local
    expose:
      - 5000
    environment:
      - FLASK_APP=/app/src/manage.py
      - FLASK_ENV=development
    networks:
      - geonet

  mariadb:
    image: library/mariadb:10.5.5
    container_name: geomaria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: geomex
    ports:
      - "3320:3306"
    volumes:
      - geodata:/var/lib/mysql:rw
    networks:
      - geonet

  nginx:
    image: library/nginx:1.19.2
    container_name: geonx
    ports:
      - "8080:80"
    depends_on:
      - geoapp
    networks:
      - geonet
    volumes:
      - ./nginx/geo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/usr/share/nginx/html/static:ro

volumes:
  geodata:

networks:
  geonet:
