version: "3.9"

services:
  geoapp:
    image: ebe/geomex:latest
    container_name: geomex
    depends_on:
      - mariadb
    build: .
    volumes:
      - ./src:/home/userapp/src:rw
      - ./requirements:/opt/requirements:rw
      - ./scripts:/opt/scripts:rw
    env_file:
      - ./.env.local
    environment:
      - GUNICORN_CMD_ARGS="--reload"
    networks:
      - geonet
    deploy:
      resources:
        limits:
          cpus: ".25"
          memory: "512MB"

  mariadb:
    image: mariadb:10.11-jammy
    container_name: geomaria
    environment:
      MARIADB_ROOT_PASSWORD: mexcret
      MARIADB_DATABASE: geomex
    ports:
      - "3306:3306"
    volumes:
      - geomaria:/var/lib/mysql:rw
    networks:
      - geonet

  nginx:
    image: nginx:1.24.0-alpine
    container_name: geox
    depends_on:
      - geoapp
    volumes:
      - ./nginx/geo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80/tcp"
      - "7070:80/tcp"
    networks:
      - geonet

volumes:
  geomaria:

networks:
  geonet:
