version: "3.9"

services:
  geoapp:
    image: ebe/geomex:latest
    depends_on:
      - mariadb
    build: .
    container_name: geomex
    volumes:
      - ./src:/home/userapp/src:rw
      - ./requirements:/opt/requirements:rw
    env_file:
      - ./.env.local
    networks:
      - geonet

  mariadb:
    image: mariadb:10.10.2-jammy
    container_name: geomaria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: geomex
    ports:
      - "3360:3306"
    volumes:
      - geodata:/var/lib/mysql:rw
    networks:
      - geonet

  nginx:
    image: nginx:1.23-alpine
    container_name: geoproxy
    ports:
      - "8080:80"
      - "7070:80"
    depends_on:
      - geoapp
    networks:
      - geonet
    volumes:
      - ./nginx/geo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/usr/share/nginx/html/static:ro

volumes:
  geodata:

networks:
  geonet:
