version: "3.8"

services:
  geoapp:
    image: ebe/geomex:latest
    depends_on:
      - mariadb
    build: .
    container_name: geomex
    volumes:
      - ./src:/home/userapp/src:rw
    env_file:
      - ./.env.local
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
    networks:
      - geonet

  migrations:
    image: ebe/geomigrate:latest
    container_name: geomigrate
    build: .
    depends_on:
      - geoapp
    env_file:
      - ./.env.local
    networks:
      - geonet
    command: flask db upgrade
    environment:
      - FLASK_ENV=development

  mariadb:
    image: mariadb:10.6.4-focal
    container_name: geomaria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: geomex
    ports:
      - "3360:3306"
    volumes:
      - geodata:/var/lib/mysql:rw
    networks:
      - geonet

  nginx:
    image: library/nginx:1.20.0-alpine
    container_name: geoproxy
    ports:
      - "8080:80"
      - "7070:80"
    depends_on:
      - geoapp
    networks:
      - geonet
    volumes:
      - ./nginx/geo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/usr/share/nginx/html/static:ro

volumes:
  geodata:

networks:
  geonet:
