version: "3.9"

services:
  geoapp:
    image: ebe/geomex:latest
    depends_on:
      - mariadb
    build: .
    container_name: geomex
    volumes:
      - ./src:/home/userapp/src:rw
      - ./requirements:/opt/requirements:rw
      - ./scripts:/opt/scripts:rw
    env_file:
      - ./.env.local
    environment:
      - GUNICORN_CMD_ARGS="--reload"
    networks:
      - geonet
    ports:
      - "8080:80"
      - "7070:80"
    deploy:
      resources:
        limits:
          cpus: ".25"
          memory: "512MB"

  mariadb:
    image: mariadb:10.10.3-jammy
    container_name: geomaria
    environment:
      MARIADB_ROOT_PASSWORD: mexcret
      MARIADB_DATABASE: geomex
    ports:
      - "3360:3306"
    volumes:
      - geomaria:/var/lib/mysql:rw
    networks:
      - geonet

volumes:
  geomaria:

networks:
  geonet:
