"""add settlement

Revision ID: 65d6abbd0643
Revises: e583df644560
Create Date: 2023-02-15 06:03:01.798838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d6abbd0643'
down_revision = 'e583df644560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhoods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhoods', schema=None) as batch_op:
        batch_op.drop_column('settlement')

    # ### end Alembic commands ###
