"""empty message

Revision ID: 7a7cc41265d7
Revises:
Create Date: 2023-01-21 06:18:46.893895

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7a7cc41265d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=30), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=90), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name='fk_states__municipalities'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name='fk_municipalities__neighborhoods'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('neighborhoods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_neighborhoods_postal_code'), ['postal_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhoods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_neighborhoods_postal_code'))

    op.drop_table('neighborhoods')
    op.drop_table('municipalities')
    op.drop_table('states')
    op.drop_table('customers')
    # ### end Alembic commands ###
