"""no username

Revision ID: 9e4e28dc86cc
Revises: f55806214614
Create Date: 2023-02-20 00:51:29.292994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e4e28dc86cc'
down_revision = 'f55806214614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=16), nullable=False))
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
