"""empty message

Revision ID: e663fa339b8e
Revises: 9e4e28dc86cc
Create Date: 2023-03-25 08:20:58.466377

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e663fa339b8e'
down_revision = '9e4e28dc86cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARBINARY(length=90),
               type_=sqlalchemy_utils.types.password.PasswordType(max_length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sqlalchemy_utils.types.password.PasswordType(length=120),
               type_=sa.VARBINARY(length=90),
               existing_nullable=False)

    # ### end Alembic commands ###
