"""zipcode

Revision ID: f55806214614
Revises: 65d6abbd0643
Create Date: 2023-02-19 05:18:55.491841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f55806214614'
down_revision = '65d6abbd0643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhoods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.String(length=5), nullable=False))
        batch_op.drop_index('ix_neighborhoods_postal_code')
        batch_op.create_index(batch_op.f('ix_neighborhoods_zipcode'), ['zipcode'], unique=False)
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighborhoods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', mysql.VARCHAR(length=5), nullable=False))
        batch_op.drop_index(batch_op.f('ix_neighborhoods_zipcode'))
        batch_op.create_index('ix_neighborhoods_postal_code', ['postal_code'], unique=False)
        batch_op.drop_column('zipcode')

    # ### end Alembic commands ###
