from os import environ

SECRET_KEY = "ytW6KzluuzsUtuP3WcbAhSZbfVUeibi0L2E5HtvB7MY"

PROPAGATE_EXCEPTIONS = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = environ['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_ENGINE_OPTIONS = {
    'connect_args': {
        'charset': 'utf8mb4'
    }
}

DEBUG = True
TEMPLATES_AUTO_RELOAD = True
SEND_FILE_MAX_AGE_DEFAULT = 0
STATIC_URL = 'http://127.0.0.1:7070/'

JWT_SECRET_KEY = "4Qcf4zDsjk4yHHSziqiVXf0o1HD3Lgk2UG1piLYi0co"
