from os import environ

SECRET_KEY = b'\x80\xf2/\xc7\xfb\xf2\xa3E\xb34OCI\xd9~.'

WTF_CSRF_ENABLED = True
WTF_CSRF_SECRET_KEY = b'\xb5.\x17W\x103^=\x9d_\t\x9d\x93\xc0\x82\xda'

PROPAGATE_EXCEPTIONS = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = environ['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_ENGINE_OPTIONS = {
    'connect_args': {
        'charset': 'utf8mb4'
    }
}

ENVIRONMENT_DEVELOPMENT_MODE = environ['FLASK_ENV'] == 'development'
DEBUG = ENVIRONMENT_DEVELOPMENT_MODE
TEMPLATES_AUTO_RELOAD = ENVIRONMENT_DEVELOPMENT_MODE
SEND_FILE_MAX_AGE_DEFAULT = 0
STATIC_URL = 'http://127.0.0.1:7070/'
